# Note: If you want to deploy to a GitHub user site (user.github.io), change baseurl to /
baseurl:
title: AA Notes
# Whether the header (with large title and subtitle) should be displayed
header: true
subtitle: Opinions based in reality
author: B. Exempt
email: bexempt [at] gmail
description: Topics of broader interest, with emphasis on irresponsible actions.
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge
baseurl: /AANotes/
permalink: /articles/:categories/:year/:month/:day/:title.html
timezone: America/NewYork
excerpt_separator: <!--more-->
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'DeployToGithub.Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
git:
  branch: src
